### ISSUE TITLE
Add /calendars endpoint

### ISSUE THREAD

**Issue by ajtran303** [the-turing-index/api#4]
- [x] Add the endpoint for `/calendars`
- [x] Needs tests
- [x] Set up Continuous Integration
- [x] Set up Continuous Deployment

**Comment by ajtran303** [comment]
## TODO

- [ ] Update and refactor the test
- [ ] Update `mod4` attribute to reflect a combined cohort
